name: CI

on: [pull_request]

jobs:

  phpunit74:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    steps:
      - uses: actions/checkout@v2

      - name: Composer dependency cache
        uses: "actions/cache@v2.0.0"
        with:
          path: "./vendor"
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        run: composer install --no-scripts --no-ansi --no-suggest --no-progress

      - name: Run test suite
        run: ./vendor/bin/phpunit

  phpunit80:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
      - uses: actions/checkout@v2

      - name: Composer dependency cache
        uses: "actions/cache@v2.0.0"
        with:
          path: "./vendor"
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        run: composer install --no-scripts --no-ansi --no-suggest --no-progress

      - name: Run test suite
        run: ./vendor/bin/phpunit
